{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "microservices.serviceAccountName" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "microservices.labels" . | nindent 4 }}
{{- end }}
