apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: todo-app
  namespace: microservices
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: todo-app
  service:
    port: 5000
    targetPort: 5000
    gateways:
      - istio-system/main-gateway
    hosts:
      - "todo.cicd.click"
  analysis:
    interval: 3m                    # ← check every 3 minutes
    threshold: 20                   # ← allow 20 failures before rollback
    maxWeight: 100                  # ← max traffic to canary before promoting
    stepWeight: 30      
