apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: todo-app
  namespace: microservices
spec:
  hosts:
    - "todo.cicd.click"
  gateways:
    - "istio-system/main-gateway"
  http:
    - route:
        - destination:
            host: todo-app
            port: 
              number: 5000

---

apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: microservices-mtls
  namespace: microservices
spec:
  host: microservices
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL


